import Mathlib.AlgebraicGeometry.EllipticCurve.Affine.Point
import Mathlib.AlgebraicTopology.SimplexCategory.Basic
import Mathlib.Analysis.SpecialFunctions.Elliptic.Weierstrass
import Mathlib.NumberTheory.ModularForms.LevelOne.GradedRing

open PeriodPair

/-!
  In this file we show the discriminant of a period pair (defined later) is non-zero.
  We first do this for `periodPair` which corresponds to the lattice generated by `1,τ`.\
-/

open Complex UpperHalfPlane EisensteinSeries ModularForm
open scoped UpperHalfPlane CongruenceSubgroup MatrixGroups

lemma linearIndependent_one_coe (τ : ℍ) : LinearIndependent ℝ ![1, (τ : ℂ)] := by
  rw [LinearIndependent.pair_iff]
  intro s t hst
  have : t * (τ : ℂ).im = 0 := by
    simpa [Complex.real_smul, Complex.add_im, Complex.mul_im] using congrArg Complex.im hst
  have : t = 0 := by
    rcases mul_eq_zero.mp this with h | h
    · exact h
    · exact absurd h (by simpa [UpperHalfPlane.coe_im] using τ.im_ne_zero)
  refine ⟨?_, this⟩
  exact_mod_cast (show (s : ℂ) = 0 by simpa [this, Complex.real_smul] using hst)

/-- The period pair `(ω₁, ω₂) = (1, τ)` attached to `τ ∈ ℍ`. Its `lattice` is `ℤ + ℤτ`. -/
def periodPair (τ : ℍ) : PeriodPair where
  ω₁ := 1
  ω₂ := τ
  indep := linearIndependent_one_coe τ

@[simp]
lemma periodPair_ω₁ (τ : ℍ) : (periodPair τ).ω₁ = 1 := rfl

@[simp]
lemma periodPair_ω₂ (τ : ℍ) : (periodPair τ).ω₂ = (τ : ℂ) := rfl

/-!
  We want to relate the G associated to these period pairs to the eisensten series.

  Specifically, they differ by a factor of the Riemann zeta function
-/

lemma G_eq_tsum_eisSummand (τ : ℍ) (k : ℕ) :
(periodPair τ).G k = ∑' v : Fin 2 → ℤ, eisSummand k v τ := by
  set L := periodPair τ with hL
  set e := ((finTwoArrowEquiv ℤ).trans (Equiv.prodComm ℤ ℤ)).trans L.latticeEquivProd.symm.toEquiv
  rw [PeriodPair.G, ← e.tsum_eq]
  refine tsum_congr fun v => ?_
  have := L.latticeEquiv_symm_apply ((Equiv.prodComm ℤ ℤ) (finTwoArrowEquiv ℤ v))
  simp only [LinearEquiv.toEquiv_symm, Equiv.trans_apply, LinearEquiv.coe_symm_toEquiv, e] at ⊢ this
  rw [this, eisSummand, zpow_neg, zpow_natCast]
  simp [hL]; ring

theorem G_eq_riemannZeta_mul_eisensteinSeries (τ : ℍ) {k : ℕ} (hk : 3 ≤ k) :
    (periodPair τ).G k = riemannZeta k * eisensteinSeries (N := 1) 0 k τ := by
  rw [G_eq_tsum_eisSummand, tsum_eisSummand_eq_riemannZeta_mul_eisensteinSeries hk]

lemma E_apply {k : ℕ} (hk : 3 ≤ k) (τ : ℍ) : (ModularForm.E hk τ : ℂ) = (1 / 2 : ℂ) *
    eisensteinSeries (N := 1) 0 k τ := by
  rfl

theorem G_eq_two_riemannZeta_mul_E (τ : ℍ) {k : ℕ} (hk : 3 ≤ k) :
    (periodPair τ).G k = 2 * riemannZeta k * (ModularForm.E hk τ : ℂ) := by
  rw [G_eq_riemannZeta_mul_eisensteinSeries τ hk, E_apply]
  ring


/-!

  We now show that the discriminant of the Weierstrass equation is non-zero

  We first require explicit values of the Bernoulli function and the Riemann Zeta function

-/

open Real

theorem bernoulli'_five : bernoulli' 5 = 0 := by
  rw [bernoulli'_def]
  norm_num [Finset.sum_range_succ, Finset.sum_range_zero, Nat.choose]

theorem bernoulli'_six : bernoulli' 6 = 1 / 42 := by
  rw [bernoulli'_def]
  norm_num [Finset.sum_range_succ, Finset.sum_range_zero, Nat.choose, bernoulli'_five]

theorem riemannZeta_six : riemannZeta 6 = (π : ℂ) ^ 6 / 945 := by
  have h := riemannZeta_two_mul_nat (k := 3) (by norm_num)
  norm_num at h
  rw [h, bernoulli_eq_bernoulli'_of_ne_one (by norm_num), bernoulli'_six]
  norm_num [Nat.factorial]
  ring

theorem zeta_const_identity : 27 * (280 * riemannZeta 6) ^ 2 = (120 * riemannZeta 4) ^ 3 := by
  rw [riemannZeta_four, riemannZeta_six]
  ring

-- Note the polynomial discrimant is 16 * this
noncomputable
abbrev weierstrassDiscriminant (L : PeriodPair) : ℂ := L.g₂ ^ 3 - 27 * L.g₃ ^ 2

lemma g₂_periodPair (τ : ℍ) :
    (periodPair τ).g₂ = 120 * riemannZeta 4 * (E₄ τ : ℂ) := by
  rw [PeriodPair.g₂, G_eq_two_riemannZeta_mul_E τ (by norm_num)]
  push_cast
  ring

lemma g₃_periodPair (τ : ℍ) : (periodPair τ).g₃ = 280 * riemannZeta 6 * (E₆ τ : ℂ) := by
  rw [PeriodPair.g₃, G_eq_two_riemannZeta_mul_E τ (by norm_num)]
  push_cast
  ring

lemma weierstrassDiscriminant_periodPair (τ : ℍ) : weierstrassDiscriminant (periodPair τ)
      = (120 * riemannZeta 4) ^ 3 * (E₄ τ ^ 3 - E₆ τ ^ 2) := by
  rw [weierstrassDiscriminant, g₂_periodPair, g₃_periodPair]
  linear_combination (-(E₆ τ ^ 2)) * zeta_const_identity

lemma E₄_cube_sub_E₆_sq_ne_zero (τ : ℍ) : E₄ τ ^ 3 - E₆ τ ^ 2 ≠ 0 :=
  fun h ↦ discriminant_ne_zero τ (by grind [discriminant_eq_E₄_cube_sub_E₆_sq])

-- this result holds for periodPair τ; but we want this for any PeriodPair
theorem weierstrassDiscriminant_periodPair_ne_zero (τ : ℍ) :
    weierstrassDiscriminant (periodPair τ) ≠ 0 := by
  rw [weierstrassDiscriminant_periodPair]
  refine mul_ne_zero (pow_ne_zero _ (mul_ne_zero (by norm_num) ?_)) (E₄_cube_sub_E₆_sq_ne_zero τ)
  exact riemannZeta_ne_zero_of_one_lt_re (by norm_num)

/-!
  Every period lattice is a scaling of `ℤ + ℤτ` for some `τ ∈ ℍ`. The candidate is the
  period ratio `ω₂ / ω₁`, which is non-real by linear independence; since `PeriodPair`
  carries no orientation the ratio may lie in the lower half-plane, in which case we
  negate it (this only reindexes the lattice by `(a, b) ↦ (a, -b)`).
-/

lemma PeriodPair.ω₁_ne_zero (L : PeriodPair) : L.ω₁ ≠ 0 := by
  simpa using L.indep.ne_zero 0

/-- The period ratio `ω₂ / ω₁` is non-real: otherwise `ω₂` would be a real multiple of `ω₁`. -/
lemma PeriodPair.im_ω₂_div_ω₁_ne_zero (L : PeriodPair) : (L.ω₂ / L.ω₁).im ≠ 0 := by
  intro h
  have hre : (L.ω₂ / L.ω₁ : ℂ) = ((L.ω₂ / L.ω₁).re : ℝ) := by
    apply Complex.ext <;> simp [h]
  have hω₂ : (L.ω₂ / L.ω₁).re • L.ω₁ = L.ω₂ := by
    have hω₁ := L.ω₁_ne_zero
    rw [Complex.real_smul, ← hre]
    field_simp
  have h0 : (L.ω₂ / L.ω₁).re • L.ω₁ + (-1 : ℝ) • L.ω₂ = 0 := by rw [hω₂]; simp
  exact absurd ((LinearIndependent.pair_iff.mp L.indep) _ _ h0).2 (by norm_num)

/-- The normalised period ratio `τ = ±(ω₂ / ω₁)`, with the sign chosen so that `τ ∈ ℍ`. -/
noncomputable def PeriodPair.τ (L : PeriodPair) : ℍ :=
  if h : 0 < (L.ω₂ / L.ω₁).im then UpperHalfPlane.mk (L.ω₂ / L.ω₁) h
  else UpperHalfPlane.mk (-(L.ω₂ / L.ω₁)) (by
    rw [Complex.neg_im, neg_pos]
    exact lt_of_le_of_ne (not_lt.mp h) L.im_ω₂_div_ω₁_ne_zero)

lemma PeriodPair.coe_τ_of_im_pos (L : PeriodPair) (h : 0 < (L.ω₂ / L.ω₁).im) :
    (L.τ : ℂ) = L.ω₂ / L.ω₁ := by
  unfold PeriodPair.τ
  rw [dif_pos h]

lemma PeriodPair.coe_τ_of_im_nonpos (L : PeriodPair) (h : ¬ 0 < (L.ω₂ / L.ω₁).im) :
    (L.τ : ℂ) = -(L.ω₂ / L.ω₁) := by
  unfold PeriodPair.τ
  rw [dif_neg h]

-- not convinced this is the correct way to package this equivalence
noncomputable
def scalingEquiv (L : PeriodPair) : L.lattice ≃ (periodPair L.τ).lattice :=
  L.latticeEquivProd.toEquiv.trans ((if 0 < (L.ω₂ / L.ω₁).im then Equiv.refl (ℤ × ℤ) else
    Equiv.prodCongr (Equiv.refl ℤ) (Equiv.neg ℤ)).trans
    (periodPair L.τ).latticeEquivProd.symm.toEquiv)

/-- `scalingEquiv` is multiplication by `ω₁⁻¹`. -/
lemma scalingEquiv_apply (L : PeriodPair) (x : L.lattice) : scalingEquiv L x = (L.ω₁)⁻¹ * x := by
  have := by simpa [L.latticeEquivProd.symm_apply_apply] using
    L.latticeEquiv_symm_apply (L.latticeEquivProd x)
  set σ : ℤ × ℤ ≃ ℤ × ℤ := if 0 < (L.ω₂ / L.ω₁).im then Equiv.refl (ℤ × ℤ)
    else Equiv.prodCongr (Equiv.refl ℤ) (Equiv.neg ℤ) with hσ
  have h : (scalingEquiv L x : ℂ) = (σ (L.latticeEquivProd x)).1 * (periodPair L.τ).ω₁
      + (σ (L.latticeEquivProd x)).2 * (periodPair L.τ).ω₂ :=
    (periodPair L.τ).latticeEquiv_symm_apply (σ (L.latticeEquivProd x))
  rw [h, this, periodPair_ω₁, periodPair_ω₂]
  by_cases h : 0 < (L.ω₂ / L.ω₁).im
  · rw [L.coe_τ_of_im_pos h, hσ, if_pos h, Equiv.refl_apply]
    field_simp [L.ω₁_ne_zero]
  · rw [L.coe_τ_of_im_nonpos h, hσ, if_neg h, Equiv.prodCongr_apply, Equiv.coe_refl,
      Equiv.neg_apply, Prod.map_fst, Prod.map_snd, id_eq]
    push_cast
    field_simp [L.ω₁_ne_zero]

/-- A bijection `e` that scales by `c` scales `Gₙ` by `c⁻ⁿ`. -/
lemma G_eq_smul_of_latticeEquiv {L L' : PeriodPair} {c : ℂ} (e : L.lattice ≃ L'.lattice)
    (he : ∀ x : L.lattice, e x = c * x) (n : ℕ) : L'.G n = (c ^ n)⁻¹ * L.G n := by
  simpa [PeriodPair.G, ← e.tsum_eq, ← tsum_mul_left] using tsum_congr fun x ↦
    by rw [he, mul_pow, mul_inv]

lemma weierstrassDiscriminant_smul_eq {L L' : PeriodPair} {c : ℂ} (hc : c ≠ 0)
    (e : L.lattice ≃ L'.lattice) (he : ∀ x, e x = c * x) :
    weierstrassDiscriminant L' = (c ^ 12)⁻¹ * weierstrassDiscriminant L := by
  simp only [weierstrassDiscriminant, PeriodPair.g₂, PeriodPair.g₃, G_eq_smul_of_latticeEquiv e he]
  field_simp

/-- The Weierstrass discriminant is nonzero for every period lattice. -/
theorem weierstrassDiscriminant_ne_zero (L : PeriodPair) : weierstrassDiscriminant L ≠ 0 := by
  refine fun _ ↦  weierstrassDiscriminant_periodPair_ne_zero L.τ ?_
  rw [weierstrassDiscriminant_smul_eq (inv_ne_zero L.ω₁_ne_zero) _ (scalingEquiv_apply L)]
  grind
